server:
   port: 8080

eureka:
   instance:
      hostname: localhost
   client:
      service-url:
         default-zone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true

spring:
   application:
      name: gateway
   main:
      web-application-type: reactive   
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lower-case-service-id: true
         routes:
         - id: MANAGEMENT-SERVICE
           uri: lb://MANAGEMENT-SERVICE
           predicates:
           - Path=/management-service/**
         - id: USER-SERVICE
           uri: lb://USER-SERVICE
           predicates:
           - Path=/user-service/**
         - id: ORDER-SERVICE
             uri: lb://ORDER-SERVICE
             predicates:
               - Path=/order-service/**