server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
#  spring.main.web-application-type=reactive
spring:
  application:
    name: gateway
    cloud:
      gateway:
        routes:
          - id: managementService
            uri: lb://MANAGEMENT-SERVICE
            predicates:
              - Path=/management-service/***