server:
   port: 8080

eureka:
   instance:
      hostname: localhost
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true

spring:
   application:
      name: gateway
   main:
      web-application-type: reactive   
   cloud:
      gateway:
         routes:
         - id: MANAGEMENT-SERVICE
           uri: lb://MANAGEMENT-SERVICE
           predicates:
           - Path=/management/**
         - id: USER-SERVICE
           uri: lb://USER-SERVICE
           predicates:
           - Path=/user/**