server:
   port: 8080

eureka:
   instance:
#     prefer-ip-address: true
      hostname: localhost
   client:
      service-url:
         default-zone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true

spring:
   application:
      name: gateway
   main:
      web-application-type: reactive   
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lower-case-service-id: true
         routes:
         - id: management
           uri: lb://management-service
           predicates:
           - Path=/management/**
         - id: user-service
           uri: lb://user-service
           predicates:
           - Path=/user/**
         - id: order-service
           uri: lb://order-service
           predicates:
             - Path=/order/**
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway